spring:
  #数据库配置
  #47.95.219.31公网地址,username:acm1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.219.31:3306/acm1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: acm1
    password: 123456
  #若不存在表，项目启动时新建表
  sql:
    init:
      schema-locations: classpath*:schema-all.sql
      mode: always

#数据库配置
mybatis-plus:
  #设置别名
  type-aliases-package: com.buct.acmer.entity
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #sql语句显示到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger配置
config:
  swagger: true

#服务器启动端口配置
server:
  port: 8089
